#!/bin/csh
#PBS -l walltime=00:05:00
#PBS -l nodes=1:ppn=1
#PBS -q classroom
#PBS -N hello_world
#PBS -j oe
##PBS -o hello_world.log.$PBS_JOBID      # by default in <jobname>.o$PBS_JOBID
#PBS -m abe
#PBS -M $USER@illinois.edu

cd $PBS_O_WORKDIR

module load openmpi
set echo ; module list ; which mpiexec   # output to aid debugging; also ldd, echo $PATH

mpiexec -np 1 hello_world                # run job in parallel using all available nodes

